version: '3'

services:
  btc-ltp-service:
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/v1/ltp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
